services:

  nginx:
    depends_on:
      - wordpress
    build: requirements/nginx/
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "$HOME/data/wordpress:/var/www/html"
    networks:
      - frontend
    env_file:
      - .env
    restart: always

  wordpress:
    depends_on:
      - mariadb
    build: requirements/wordpress/
    image: wordpress
    container_name: wordpress
    ports:
      - "9000:9000"
    volumes:
      - "$HOME/data/wordpress:/var/www/html"
    networks:
      - frontend
      - backend
    env_file:
      - .env
    restart: always

  mariadb:
    build: requirements/mariadb/
    image: mariadb
    container_name: mariadb
    ports:
      - "3306:3306"
    volumes:
      - "$HOME/data/mariadb:/var/lib/mysql"
    networks:
      - backend
    env_file:
      - .env
    restart: always

networks:
  frontend:
  backend:
