services:
  nginx:
    build: ./requirements/nginx
    image: nginx
    container_name: nginx
    env_file:
      - .env
    ports:
      - 443:443
    restart: always

  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    volumes:
      - wp:/var/www/html
    env_file:
      - .env
    restart: always

volumes:
  wp:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/$USER/data/wordpress
