version: '3'
services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    env_file:
      - .env
    ports:
      - 443:443
      # - 8080:80 test tools/index.html
    restart: always
